# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91542e134a149de91d517a5e917caa0f8b2669c353fb5126fb3e2c4dd8eba316f8d23bccab520d2727fe8013f9695f14dfbcfcf428220243d7555a62cd6aa2b9

test:
  secret_key_base: 79401c09efffb52f6858768fa79fc9d70b08a342460ea628909979a78e5fcd4a37aa491060239ffd57be552220b04869c58f6d16d79ee891579707e39ddc75a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
